const buzzerSound = "./sounds/buzzer.mp3";
const chimeSound = "./sounds/chime.mp3";
const soundArray = [
            ["i", "./sounds/cfu01.mp3"],
            ["i", "./sounds/cfu02.mp3"],
            ["i", "./sounds/cfu03.mp3"],
            ["i", "./sounds/cfu04.mp3"],
            ["ɛ", "./sounds/omfu01.mp3"],
            ["ɛ", "./sounds/omfu02.mp3"],
            ["ɛ", "./sounds/omfu03.mp3"],
            ["ɛ", "./sounds/omfu04.mp3"],
            ["æ", "./sounds/nofu01.mp3"],
            ["æ", "./sounds/nofu02.mp3"],
            ["æ", "./sounds/nofu03.mp3"],
            ["æ", "./sounds/nofu04.mp3"],
            ["a", "./sounds/ofu01.mp3"],
            ["a", "./sounds/ofu02.mp3"],
            ["a", "./sounds/ofu03.mp3"],
            ["a", "./sounds/ofu04.mp3"],
            ["ɑ", "./sounds/obu01.mp3"],
            ["ɑ", "./sounds/obu02.mp3"],
            ["ɑ", "./sounds/obu03.mp3"],
            ["ɑ", "./sounds/obu04.mp3"],
            ["ɒ", "./sounds/obr01.mp3"],
            ["ɒ", "./sounds/obr02.mp3"],
            ["ɒ", "./sounds/obr03.mp3"],
            ["ɒ", "./sounds/obr04.mp3"],
            ["ɔ", "./sounds/ombr01.mp3"],
            ["ɔ", "./sounds/ombr02.mp3"],
            ["ɔ", "./sounds/ombr03.mp3"],
            ["ɔ", "./sounds/ombr04.mp3"],
            ["u", "./sounds/cbr01.mp3"],
            ["u", "./sounds/cbr02.mp3"],
            ["u", "./sounds/cbr03.mp3"],
            ["u", "./sounds/cbr04.mp3"],
            ["ɪ", "./sounds/ncnfu01.mp3"],
            ["ɪ", "./sounds/ncnfu02.mp3"],
            ["ɪ", "./sounds/ncnfu03.mp3"],
            ["ɪ", "./sounds/ncnfu04.mp3"],
            ["ʊ", "./sounds/ncnbr01.mp3"],
            ["ʊ", "./sounds/ncnbr02.mp3"],
            ["ʊ", "./sounds/ncnbr03.mp3"],
            ["ʊ", "./sounds/ncnbr04.mp3"],
            ["ə", "./sounds/mc01.mp3"],
            ["ə", "./sounds/mc02.mp3"],
            ["ə", "./sounds/mc03.mp3"],
            ["ə", "./sounds/mc04.mp3"],
        ];
